var bookingUrl='https://booksy.com/pl-pl/210437_beauty-by-soyka_brwi-i-rzesy_4669_siedlce#ba_s=seo';
var services=[['Regulacja brwi','','50,00 zł','15 min'],['Farba + regulacja','Dobranie kształtu i koloru brwi do kształtu twarzy, włosów i karnacji.','100,00 zł','30 min'],['Laminacja brwi + farbka + regulacja','Laminacja, farbowanie, dobranie kształtu, regulacja i pielęgnacja.','140,00 zł','45 min'],['Henna + regulacja','','100,00 zł','30 min'],['Henna brwi + henna rzęs','','140,00 zł','40 min'],['Laminacja brwi + laminacja rzęs zestaw','Pakiet: laminacja brwi oraz farbka i regulacja, laminacja rzęs oraz farbowanie.','280,00 zł','1 godz.'],['Laminacja rzęs + farbka + BOTOX','Laminacja rzęs, farbowanie i BOTOX.','140,00 zł','45 min'],['Farbowanie rzęs','','40,00 zł','15 min'],['Makijaż dzienny','','220,00 zł','40 min'],['Makijaż OKAZJONALNY','Makijaż z kępkami rzęs oraz dekoltem.','250,00 zł','1 godz.'],['Makijaż wieczorowy','Makijaż z kępkami rzęs oraz dekoltem.','250,00 zł','1 godz.'],['Makijaż ślubny','','280,00 zł','1 godz. 30 min'],['Makijaż okazjonalny niedziela i święta','','300,00 zł','1 godz.'],['Konsultacja makijażu permanentnego','','Darmowa','15 min'],['Korekta permanentnego makijażu za miesiąc','','200,00 zł','1 godz.'],['Permanentny makijaż','','800,00 zł','2 godz.'],['Depilacja twarzy woskiem','','20,00 zł','10 min'],['Regulacja brwi męska','','50,00 zł','10 min'],['Przekłuwanie uszu dziecku','Przekłucie uszu na jedno urządzenie, cena bez kolczyków + 50 zł kolczyki.','200,00 zł+','30 min'],['Piercing','','150,00 zł','30 min'],['Konsultacja','Cena promocyjna.','5,00 zł','30 min']];
var faqs=[['Jak umówić wizytę?','Najwygodniej przez Booksy albo telefonicznie pod numerem 511 230 234.'],['Gdzie znajduje się salon?','Beauty by Soyka mieści się przy ul. Warszawskiej 125/53 w Siedlcach.'],['Czy salon pracuje w poniedziałki?','Nie. Salon jest zamknięty w niedziele i poniedziałki.'],['Jak długo trwa laminacja brwi?','Najczęściej około 45 minut, zależnie od zakresu stylizacji.'],['Czy makijaż okazjonalny obejmuje kępki rzęs?','Tak, w opisie usługi uwzględnione są kępki rzęs oraz dekolt.'],['Czy można zrobić makijaż ślubny?','Tak, makijaż ślubny jest dostępny w cenniku.'],['Czy wykonywana jest regulacja brwi męska?','Tak, usługa regulacji brwi męskiej jest dostępna.'],['Czy cena konsultacji jest stała?','W cenniku widoczna jest cena promocyjna 5 zł. Warto potwierdzić aktualną cenę przy rezerwacji.'],['Czy można wykonać piercing?','Tak, salon ma w ofercie piercing oraz przekłuwanie uszu dziecku.'],['Czy trzeba przygotować się do laminacji rzęs?','Najlepiej przyjść bez makijażu oka i nie stosować tłustych kosmetyków przed wizytą.'],['Czy po zabiegu można moczyć rzęsy?','Po laminacji warto stosować się do zaleceń pozabiegowych przekazanych w salonie.'],['Czy oferta jest aktualna?','Cennik przygotowano na podstawie widocznej rezerwacji online. Przed wizytą warto sprawdzić Booksy.']];
var header=document.querySelector('[data-header]');var navToggle=document.querySelector('[data-nav-toggle]');var priceRoot=document.querySelector('[data-prices]');var faqRoot=document.querySelector('[data-faq]');var cookie=document.querySelector('[data-cookie]');var closeCookie=document.querySelector('[data-cookie-close]');
window.addEventListener('load',function(){document.body.classList.add('loaded')});window.addEventListener('scroll',function(){header.classList.toggle('is-scrolled',window.scrollY>24)});navToggle&&navToggle.addEventListener('click',function(){header.classList.toggle('is-open')});document.querySelectorAll('[data-nav] a').forEach(function(link){link.addEventListener('click',function(){header.classList.remove('is-open')})});
priceRoot.innerHTML=services.map(function(s){return '<article class="price-row"><div><h3>'+s[0]+'</h3>'+(s[1]?'<p class="price-desc">'+s[1]+'</p>':'')+'</div><div class="price-meta"><strong>'+s[2]+'</strong><span>'+s[3]+'</span></div><a class="book-btn" href="'+bookingUrl+'" target="_blank" rel="noreferrer">Umów</a></article>'}).join('');
faqRoot.innerHTML=faqs.map(function(f,i){return '<article class="faq-item '+(i===0?'is-open':'')+'"><button class="faq-question" type="button" aria-expanded="'+(i===0)+'">'+f[0]+'<span>'+(i===0?'-':'+')+'</span></button><p class="faq-answer">'+f[1]+'</p></article>'}).join('');
document.querySelectorAll('.faq-question').forEach(function(button){button.addEventListener('click',function(){var item=button.closest('.faq-item');var isOpen=item.classList.toggle('is-open');button.setAttribute('aria-expanded',String(isOpen));button.querySelector('span').textContent=isOpen?'-':'+'})});
var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(function(el){observer.observe(el)});
var countElement=document.querySelector('[data-count]');if(countElement){var value=0;var target=Number(countElement.dataset.count);var timer=setInterval(function(){value+=Math.ceil(target/45);if(value>=target){value=target;clearInterval(timer)}countElement.textContent=value},28)}
if(localStorage.getItem('soyka-cookie-ok')!=='true'){cookie&&cookie.classList.add('is-visible')}closeCookie&&closeCookie.addEventListener('click',function(){localStorage.setItem('soyka-cookie-ok','true');cookie&&cookie.classList.remove('is-visible')});
var darkButton=document.createElement('button');darkButton.type='button';darkButton.className='header-cta';darkButton.textContent='Tryb';darkButton.setAttribute('aria-label','Przełącz tryb jasny i ciemny');document.querySelector('.site-header')&&document.querySelector('.site-header').appendChild(darkButton);darkButton.addEventListener('click',function(){document.body.classList.toggle('dark')});
